---
- hosts: mysql-1
  remote_user: vagrant
  sudo: true
  vars:
    - reset_admin_password: false
    - keepalived_vip: 192.168.250.100
    - wordpress_db: wordpress
    - wordpress_admin_password: $P$B3gD8U9JnM20wPg5n242eJhhuBVhvr0  #default is admin; generate new password here http://www.miraclesalad.com/webtools/md5.php
    - wordpress_admin_user: admin
    - wordpress_update_db_site_file: /tmp/update_db_site.sql
  tasks:
# The tasks below fix an issue with the wordpress site URL temporarily until a real fix has been created
    - name: uploading update_db_site sql file
      template: src=templates/update_db_site.sql.j2 dest={{ wordpress_update_db_site_file }}

    - name: fixing DB
      mysql_db: state=import name={{ wordpress_db }} target={{ wordpress_update_db_site_file }}
